### ISSUE TITLE
Protocol support for non-java languages

### ISSUE THREAD

**Issue by maxverbeek** [andrewlalis/Concord#2]
Dear Concord maintainer,

I would wish for a serialisation format that is friendlier to non-java languages so that I can implement my own Concord client in an inferior programming language such as Bash or Rust.

Sincerely,

A Concord enthusiast.

PS nice music in your video

**Comment by andrewlalis** [comment]
Hello Concord enthusiast!

As of right now, the serialisation format should be designed to be quite simple to use for any programming language; maybe it's just quite a bit convoluted to see that from the java code.

Each network message that's sent, either client -> server or server -> client, follows this format:

- 1 byte which contains the message type, where the message types are defined in the mapping [here](https://github.com/andrewlalis/Concord/blob/main/core/src/main/java/nl/andrewl/concord_core/msg/Serializer.java).
- All remaining bytes of a message may be defined by the type of message that is sent. So the first *type* byte defines the logic which you should use when reading or writing messages of that type.

There are some common conventions that are used to simplify each message type's responsibilities, however:
- All strings are written with a 4-byte integer prefix which indicates their length, followed directly by that number of bytes.
- All enumerations are written as a 4-byte integer denoting their ordinality.
- All UUIDs are written as a 16-byte combination of the UUID's most significant bits followed by its least significant bits.
- Lists of messages can be encoded using a 4-byte integer prefix denoting the number of messages contained within, followed by the number of messages.

It should be pretty clear what each message type entails, from the [types package](https://github.com/andrewlalis/Concord/tree/main/core/src/main/java/nl/andrewl/concord_core/msg/types), but I do agree that it could do with a lot more documentation if this system is actually going to be used in multiple places.

Also, is there anything about this protocol which is specifically difficult to implement for a language like Rust? I actually designed the messaging to not use a type hierarchy, so it should be possible to create a `Message` trait like the `Message` interface, although I am not sure about rust's abilities to generate new instances of objects based on a type, like how I do [here](https://github.com/andrewlalis/Concord/blob/96fd07b3fef8caded028d0a46441f1d0d7fcfc49/core/src/main/java/nl/andrewl/concord_core/msg/Serializer.java#L34).

**Comment by maxverbeek** [comment]
My apologies. I was under the impression that this was using an ObjectOutputstream, I had missed the read and write implementations on each message type entirely.

You can expect a contribution to the Concord ecosystem in the near future when I have some time.
